// title: String(vehicle.name),
// description: String(vehicle.description),
// channels: ["marketplace"],
// "pictures": [
//     {
//       "source":"https://cdn.pixabay.com/photo/2017/06/15/04/13/car-2404064__340.png"
//     },
//     {
//       "source":"https://cdn.pixabay.com/photo/2018/03/06/19/44/mercedes-benz-3204364__340.png"
//     },
// ],
// category_id: "MLB76395",
// price: String(vehicle.price),
// currency_id: "BRL",
// listing_type_id: "free",
// available_quantity: "1",
// location: {
//     address_line: "Avenida Juruce, 436",
//     zip_code: "04080011",
//     city: { id: "BR-SP-56" }
// },
// attributes: [
//     { id: "BRAND", value_name: String(vehicle.brand) },
//     { id: "MODEL", value_name: String(vehicle.model) },
//     { id: "VEHICLE_YEAR", value_name: String(vehicle.year) },
//     { id: "DOORS", value_name: String(vehicle.doorQuantity) },
//     { id: "KILOMETERS", value_name: String(vehicle.mileage) },
//     { id: "FUEL_TYPE", value_name: String(vehicle.fuelType) },
//     { id: "COLOR", value_name: String(vehicle.color) },
//     { id: "STEERING", value_name: "Elétrica" },
//     { id: "CONTACT_SCHEDULE", value_name: "Me procurar a tarde" },
//     { id: "TRANSMISSION", value_name: "Automática" },
//     { id: "TRACTION_CONTROL", value_name: "Dianteira" },
//     { id: "ARMORED", value_name: "Sim" },
//     { id: "HAS_ABS_BRAKES", value_name: "Sim" },
//     { id: "HAS_AIR_CONDITIONING", value_name: "Sim" },
//     { id: "HAS_ALARM", value_name: "Sim" },
//     { id: "HAS_ALLOY_WHEELS", value_name: "Sim" },
//     { id: "HAS_AMFM_RADIO", value_name: "Sim" },
//     { id: "HAS_AUXILIARY_PORT", value_name: "Sim" },
//     { id: "ITEM_CONDITION", value_name: "Novo" },
//     { id: "LICENSE_PLATE", value_name: "EWP5306" },
//     { id: "PASSENGER_CAPACITY", value_name: "8" },
//     { id: "TRIM", value_name: "XRS" },
//     { id: "SINGLE_OWNER", value_name: "Sim" },
//     { id: "HAS_WINDSCREEN_WIPER", value_name: "Sim" },
//     { id: "HAS_USB", value_name: "Sim" },
//     { id: "HAS_STEERING_WHEEL_CONTROL", value_name: "Sim" },
//     { id: "HAS_POWER_DOOR_LOCKS", value_name: "Sim" },
//     { id: "HAS_POWER_WINDOWS", value_name: "Sim" },
//     { id: "HAS_RAIN_SENSOR", value_name: "Sim" },
//     { id: "HAS_REAR_FOGLIGHTS", value_name: "Sim" },
//     { id: "HAS_HEIGHT_ADJUSTABLE_DRIVER_SEAT", value_name: "Sim" },
//     { id: "HAS_SLIDING_ROOF", value_name: "Sim" },
//     { id: "HAS_LEATHER_UPHOLSTERY", value_name: "Sim" },
//     { id: "HAS_LIGHT_ON_REMINDER", value_name: "Sim" },
//     { id: "HAS_MP3_PLAYER", value_name: "Sim" },
//     { id: "HAS_ONBOARD_COMPUTER", value_name: "Sim" },
//     { id: "HAS_PARKING_SENSOR", value_name: "Sim" },
//     { id: "HAS_PASSENGER_AIRBAG", value_name: "Sim" },
//     { id: "TRANSMISSION", value_name: "Automática" },
//     { id: "VEHICLE_BODY_TYPE", value_name: "Minivan" },
//     { id: "HEIGHT", value_name: "1625 mm" },
//     { id: "WIDTH", value_name: "1800 mm" },
//     { id: "DISTANCE_BETWEEN_AXES", value_name: "2570 mm" },
//     { id: "FUEL_CAPACITY", value_name: "54 L" },
//     { id: "LENGTH", value_name: "4140 mm" },
//     { id: "VALVES_PER_CYLINDER", value_name: "4" },
//     { id: "GEAR_NUMBER", value_name: "6" },
//     { id: "HAS_CURTAIN_AIRBAG", value_name: "Sim" },
//     { id: "HAS_FOG_LIGHT", value_name: "Sim" },
//     { id: "HAS_REAR_FOLDING_SEAT", value_name: "Sim" },
//     { id: "HAS_ELECTRIC_MIRRORS", value_name: "Sim" },
//     { id: "HAS_AUTOPILOT", value_name: "Sim" }
// ]
// };